#!/usr/bin/env python3
"""
Convert an API test report (generated by the Ops Dashboard) into the format
expected by the "Test from JSON" endpoint (the same structure as
response_1774584527890.json).

Usage:
    python convert_report_to_json.py api_test_report_2026-03-27T04-03-43.json output.json
"""

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from urllib.parse import urlparse

BASE_URL = "https://awareness-ai.com.br"   # adjust if needed


def extract_path(full_url: str) -> str:
    """Extract the path component from a full URL, stripping the base URL."""
    parsed = urlparse(full_url)
    return parsed.path


def clean_summary(raw_name: str) -> str:
    """Extract a clean summary from the test result's 'name' field.
    Examples:
        "index [GET /]" -> "index"
        "Health [GET /health]" -> "Health"
    """
    if "[" in raw_name:
        return raw_name.split("[", 1)[0].strip()
    return raw_name


def convert_report(report_path: str) -> dict:
    with open(report_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    results = data.get("results", [])
    services = defaultdict(list)

    for ep in results:
        # Skip entries where the test failed to produce a URL (should not happen)
        url = ep.get("url", "")
        if not url:
            continue

        method = ep.get("method", "GET").upper()
        path = extract_path(url)
        # Some paths might be empty – skip
        if not path:
            continue

        summary = clean_summary(ep.get("name", ""))

        # Use the service name as it appears in the test report
        service_name = ep.get("group", "Unknown")

        services[service_name].append({
            "method": method,
            "path": path,
            "summary": summary,
        })

    # Build the final output
    output_services = []
    for name, endpoints in services.items():
        eps_dict = {}
        for ep in endpoints:
            key = f"{ep['method']} {ep['path']}"
            eps_dict[key] = {
                "method": ep["method"],
                "path": ep["path"],
                "summary": ep["summary"],
                "description": ep["summary"],   # reuse summary as description
                # The operationId is not needed for the JSON test input; we can omit
            }
        output_services.append({
            "name": name,
            "total_endpoints": len(eps_dict),
            "endpoints": eps_dict,
        })

    result = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "gateway_version": "1.0.0",   # placeholder
        "services": output_services,
    }
    return result


def main():
    if len(sys.argv) < 2:
        print("Usage: python convert_report_to_json.py input_report.json [output.json]")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "converted_endpoints.json"

    converted = convert_report(input_file)
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(converted, f, indent=2, ensure_ascii=False)

    print(f"Converted {len(converted['services'])} services to {output_file}")


if __name__ == "__main__":
    main()